easy_admin:
      formats:
        date: 'd/m/Y'

      design:
        brand_color: red
        menu:
          - { label: 'Réservation'}
          - { label: 'Nouvelle Réservation', entity: 'Booking', icon: 'plus',params: {action: 'new'} }
          - { label: 'Réservation', entity: 'Booking', icon: 'calendar', params: { sortField: 'bookingDate', sortDirection: 'DESC' } }
          - { label: 'Réservation du jour', route: 'resa_day', rel: 'resa-day', target: _blank }
          - { label: 'Autres'}
          - { label: 'Client', entity: 'User', icon: 'user',  params: { sortField: 'name', sortDirection: 'ASC' }}
          - { label: 'Séance', entity: 'Meeting', icon: 'clock', params: { sortField: 'id', sortDirection: 'ASC' } }
          - { label: 'Bloqué une date', entity: 'DateBlocked', icon: 'clock', params: { sortField: 'blockedDate', sortDirection: 'DESC' }}
          - { label: 'Paiement', entity: 'Paypal'}
