easy_admin:
    entities:
      Booking:
        class: App\Entity\Booking
        list:
          collapse_actions: true
          actions: ['show', 'edit', 'delete']
          fields:
            - {property: 'name', label: 'ID'}
            - {property: 'createAt', label: 'Crée le', format: 'd/m/y H:m:s'}
            - {property: 'bookingDate', label: 'Date'}
            - {property: 'user', label: 'Client'}
            - {property: 'room', label: 'Salle'}
            - {property: 'meeting', label: 'Séance'}
            - {property: 'nbPerson', label: 'Nb'}
            - {property: 'user.number', type: 'tel', label: 'Contact'}
            - {property: 'payment', label: 'Acompte'}
            - {property: 'total', label: 'Total'}
            - {property: 'notices', label: 'Remarques'}
        form:
          fields:
            - { type: 'group', columns: 4, label: 'Basic information' }
            - {property: 'name', label: 'Nom de la reservation', type_options: { disabled: true }}
            #- {property: 'paiement'}
            - {property: 'total', label: 'Total (€)'}
            - {property: 'notices'}
            - { type: 'group', columns: 8, label: 'Information réservation' }
            - {label: 'Date de la réservation' , property: 'bookingDate', type_options: { widget: 'single_text' }}
            - {property: 'room', label: 'Salle'}
            - {property: 'meeting', label: "séance"}
            - {property: 'nbPerson', label: 'Nombre de personne'}

        search:
          fields: ['user.nom', 'user.email', 'user.number', 'bookingDate', 'name', 'user']
